module.exports = [
  {
    id: 1,
    mental_vibe: "Neutral",
    emotional_vibe: "Neutral",
    rating: null,
    movie_id: 1,
    user_id: 1,
    watched: false,
  },
  {
    id: 2,
    mental_vibe: "Thought-provoking",
    emotional_vibe: "Heavy-hearted",
    rating: 8,
    movie_id: 2,
    user_id: 1,
    watched: true,
  },
  {
    id: 3,
    mental_vibe: "Brainless",
    emotional_vibe: "Light-hearted",
    rating: 5,
    movie_id: 3,
    user_id: 1,
    watched: true,
  },
  {
    id: 4,
    mental_vibe: "Neutral",
    emotional_vibe: "Heavy-hearted",
    rating: null,
    movie_id: 4,
    user_id: 1,
    watched: false,
  },
  {
    id: 5,
    mental_vibe: "Thought-provoking",
    emotional_vibe: "Neutral",
    rating: 7,
    movie_id: 5,
    user_id: 1,
    watched: true,
  },
  {
    id: 6,
    mental_vibe: "Brainless",
    emotional_vibe: "Light-hearted",
    rating: null,
    movie_id: 6,
    user_id: 1,
    watched: false,
  },
  {
    id: 7,
    mental_vibe: "Neutral",
    emotional_vibe: "Neutral",
    rating: 4,
    movie_id: 7,
    user_id: 1,
    watched: true,
  },
  {
    id: 8,
    mental_vibe: "Thought-provoking",
    emotional_vibe: "Heavy-hearted",
    rating: 9,
    movie_id: 8,
    user_id: 1,
    watched: true,
  },
];
