module.exports = [
  {
    id: 1,
    mental_vibe: "Neutral",
    emotional_vibe: "Neutral",
    rating: null,
    movie_id: 346698,
    user_id: 1,
    watched: false,
  },
  {
    id: 2,
    mental_vibe: "Thought-provoking",
    emotional_vibe: "Heavy-hearted",
    rating: 8,
    movie_id: 565770,
    user_id: 1,
    watched: true,
  },
  {
    id: 3,
    mental_vibe: "Brainless",
    emotional_vibe: "Light-hearted",
    rating: 5,
    movie_id: 872585,
    user_id: 1,
    watched: true,
  },
  {
    id: 4,
    mental_vibe: "Neutral",
    emotional_vibe: "Heavy-hearted",
    rating: null,
    movie_id: 447365,
    user_id: 1,
    watched: false,
  },
  {
    id: 5,
    mental_vibe: "Thought-provoking",
    emotional_vibe: "Neutral",
    rating: 7,
    movie_id: 11430,
    user_id: 1,
    watched: true,
  },
  {
    id: 6,
    mental_vibe: "Brainless",
    emotional_vibe: "Light-hearted",
    rating: null,
    movie_id: 297708,
    user_id: 1,
    watched: false,
  },
  {
    id: 7,
    mental_vibe: "Neutral",
    emotional_vibe: "Neutral",
    rating: 4,
    movie_id: 592896,
    user_id: 1,
    watched: true,
  },
];
