module.exports = [
  {
    id: 1,
    mental_vibe: "Neutral",
    emotional_vibe: "Neutral",
    rating: null,
    movieId: 1,
    userId: 1,
    watched: false,
  },
  {
    id: 2,
    mental_vibe: "Thought-provoking",
    emotional_vibe: "Heavy-hearted",
    rating: 8,
    movieId: 2,
    userId: 1,
    watched: true,
  },
  {
    id: 3,
    mental_vibe: "Brainless",
    emotional_vibe: "Light-hearted",
    rating: 5,
    movieId: 3,
    userId: 1,
    watched: true,
  },
  {
    id: 4,
    mental_vibe: "Neutral",
    emotional_vibe: "Heavy-hearted",
    rating: null,
    movieId: 4,
    userId: 1,
    watched: false,
  },
  {
    id: 5,
    mental_vibe: "Thought-provoking",
    emotional_vibe: "Neutral",
    rating: 7,
    movieId: 5,
    userId: 1,
    watched: true,
  },
  {
    id: 6,
    mental_vibe: "Brainless",
    emotional_vibe: "Light-hearted",
    rating: null,
    movieId: 6,
    userId: 1,
    watched: false,
  },
  {
    id: 7,
    mental_vibe: "Neutral",
    emotional_vibe: "Neutral",
    rating: 4,
    movieId: 7,
    userId: 1,
    watched: true,
  },
  {
    id: 8,
    mental_vibe: "Thought-provoking",
    emotional_vibe: "Heavy-hearted",
    rating: 9,
    movieId: 8,
    userId: 1,
    watched: true,
  },
];
